### ISSUE TITLE
Solutions to Katas 

### ISSUE THREAD

**Issue by Besuf** [swkBerlin/kata-bootstraps#223]
Hey there, I wrote this as an issue because I don't know where else to write questions or suggestions about https://kata-log.rocks/. So, I just implemented my first kata.  The thing is I'd like to know if my implementation is good enough by comparing my work to an answer / codebase given for a kata. The individual Katas are really nice and also helps you target specific weaknesses. However, I don't see all of this helping to the full potential unless there's a way we can compare our implementation probably to the implementation of the question creator. Any directions to address this case would be much obliged :)

**Comment by coulas** [comment]
Katas solution is more about your way of working, your methodology than an implementation result.
Their value is in the discussion, the "**why** did write those lines that way ?"
The repository you are looking for is probably : https://github.com/advent-of-craft/advent-of-craft
Where you'll find programming exercises and solutions.
You are welcome to also join the discussion on their associated Discord.
Happy coding !

**Comment by Besuf** [comment]
Thank you, guys, for the explanation!
