### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hajotka** [swkBerlin/kata-bootstraps#6]
First, thanks a lot for putting these bootstrap projects out there!

I was wondering what the license for this code is, there seems to be none specified. It would be nice if you specify one so that there is no uncertainty when using this repository.

**Comment by madduci** [comment]
+1

**Comment by sils** [comment]
Pleasepleaseplease, put a l icense! CC @holsky

**Comment by mrksdck** [comment]
Ok, so lets get a license.
I would go with [MIT](https://choosealicense.com/licenses/mit/) license.
I kindly ask all contributors to answer/comment if you are ok with that license : @christof-vollrath @ikusalic @madduci @Egga @FlorianKempenich @robertfirek @BooleanCat @deniseyu @mkrogemann 
If all are in ok with this license, then I'll add it to the root of this repo.

**Comment by Egga** [comment]
I'm ok

**Comment by madduci** [comment]
For me MIT or BSD are totally fine

**Comment by christof-vollrath** [comment]
fine

**Comment by dcarral** [comment]
Hey @mrksdck, let's rescue this (IMHO important) issue ;) 
I'd propose to go ahead and include the license right away (perhaps re-mentioning users who haven't reacted to your request yet?). Thoughts?

**Comment by robertfirek** [comment]
Fine

**Comment by holsky** [comment]
@dcarral sounds reasonable, I'd do that at 12-31 if nobody screams.

 @ikusalic @FlorianKempenich @BooleanCat @deniseyu have time until then :)

**Comment by mrksdck** [comment]
Thank you for the nudge @dcarral and thanks @holsky for taking over :+1:
